# Appended to page title
title: "Uniformed HTML"


# CSS Configuration Settings
normalize: true  # Import normalize? (v8.0.1, github.com/necolas/normalize.css)
bootstrap: false  # Import bootstrap? (v5.1.3, getbootstrap.com)
customCSS: false # Import custom CSS?

# JS Configuration settings
customJS: false # Import custom JS?
